name: my_first_workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use the latest version

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -e .  # Install package in editable mode
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: python -m unittest discover tests
