name: my_first_workflow

on: [push, pull_request]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use the latest version

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel  # Upgrade pip and setuptools

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install dependencies
          pip install -e .  # Install package in editable mode

      - name: Verify installation
        run: pip list  # Check installed packages for debugging

      - name: Run tests
        run: |
          mkdir -p test-results  # Ensure the test-results directory exists
          python -m unittest discover tests > test-results/results.txt  # Save test results

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/results.txt  # Correct path to upload the artifact
